# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/country.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/country.proto", :syntax => :proto3) do
    add_message "protobuf.Country" do
      optional :id, :int64, 1
      optional :name, :string, 2
      optional :country_code, :message, 3, "google.protobuf.StringValue"
      optional :currency, :string, 4
      optional :capital, :string, 5
      optional :independent, :message, 6, "google.protobuf.BoolValue"
      optional :established, :message, 7, "google.protobuf.Int64Value"
    end
  end
end

module Protobuf
  Country = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Country").msgclass
end
