# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/optional.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/optional.proto", :syntax => :proto3) do
    add_message "protobuf.Optional" do
      oneof :type do
        optional :int32, :int32, 1
        optional :int64, :int64, 2
        optional :string, :string, 3
        optional :check, :bool, 4
      end
    end
  end
end

module Protobuf
  Optional = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Optional").msgclass
end
