# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/person.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/person.proto", :syntax => :proto3) do
    add_message "protobuf.Person" do
      optional :id, :uint32, 2
      optional :name, :string, 1
      optional :is_active, :bool, 3
    end
  end
end

module Protobuf
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Person").msgclass
end
