# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/survey.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/survey.proto", :syntax => :proto3) do
    add_message "protobuf.Survey" do
      optional :question, :enum, 1, "protobuf.Survey.Question"
      optional :answer, :enum, 2, "protobuf.Survey.Answer"
    end
    add_enum "protobuf.Survey.Answer" do
      value :ANSWER_A, 0
      value :ANSWER_B, 1
      value :ANSWER_C, 2
    end
    add_enum "protobuf.Survey.Question" do
      value :QUESTION_A, 0
      value :QUESTION_B, 1
      value :QUESTION_C, 2
    end
  end
end

module Protobuf
  Survey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Survey").msgclass
  Survey::Answer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Survey.Answer").enummodule
  Survey::Question = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Survey.Question").enummodule
end
