# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/task.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/task.proto", :syntax => :proto3) do
    add_message "protobuf.Task" do
      proto3_optional :id, :int64, 1
      proto3_optional :name, :string, 2
      proto3_optional :completed, :bool, 6
    end
  end
end

module Protobuf
  Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Task").msgclass
end
